### ISSUE TITLE
Was assisting to the meetup at Guadalajara a requirement to participate?

### ISSUE THREAD

**Issue by cosmeoes** [Zubale/zubale-backend-challenge#2]
We were at Talent Land last week and a Zubale's team member told us about this challenge on Thursday. It sounded very interesting and we were hoping to start working on it once we were back home.

So we didn't attend the meetup, but we were wondering if we could participate anyway in this challenge or was attending to the meetup an absolute requirement to participate?

**Comment by samschifman** [comment]
You can certainly still participate in the challenge. All you need to do is follow the instructions in the readme and fork this repo. Please remember to include contact information in your submission.

Attending the meetup was optional. 

Please let us know if you have any other questions.

**Comment by cosmeoes** [comment]
Thank you!.
